<?php

namespace App\Modules\School\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['id' => 4, 'name' => 'AFGHANISTAN', 'nationality' => 'Afghane', 'iso_code_2' => 'AF', 'iso_code_3' => 'AFG', 'phone_code' => '93', 'continent' => 'AS', 'is_active' => true],
            ['id' => 8, 'name' => 'ALBANIE', 'nationality' => 'Albanaise', 'iso_code_2' => 'AL', 'iso_code_3' => 'ALB', 'phone_code' => '355', 'continent' => 'EU', 'is_active' => true],
            ['id' => 10, 'name' => 'ANTARCTIQUE', 'nationality' => 'Antarctique', 'iso_code_2' => 'AQ', 'iso_code_3' => 'ATA', 'phone_code' => '672', 'continent' => 'AN', 'is_active' => true],
            ['id' => 12, 'name' => 'ALGÉRIE', 'nationality' => 'Algérienne', 'iso_code_2' => 'DZ', 'iso_code_3' => 'DZA', 'phone_code' => '213', 'continent' => 'AF', 'is_active' => true],
            ['id' => 16, 'name' => 'SAMOA AMÉRICAIN', 'nationality' => 'Américaine des Samoa', 'iso_code_2' => 'AS', 'iso_code_3' => 'ASM', 'phone_code' => '684', 'continent' => 'OC', 'is_active' => true],
            ['id' => 20, 'name' => 'ANDORRE', 'nationality' => 'Andorrane', 'iso_code_2' => 'AD', 'iso_code_3' => 'AND', 'phone_code' => '376', 'continent' => 'EU', 'is_active' => true],
            ['id' => 24, 'name' => 'ANGOLA', 'nationality' => 'Angolaise', 'iso_code_2' => 'AO', 'iso_code_3' => 'AGO', 'phone_code' => '244', 'continent' => 'AF', 'is_active' => true],
            ['id' => 28, 'name' => 'ANTIGUA-ET-BARBUDA', 'nationality' => 'Antiguaise-et-Barbudienne', 'iso_code_2' => 'AG', 'iso_code_3' => 'ATG', 'phone_code' => '268', 'continent' => 'NA', 'is_active' => true],
            ['id' => 31, 'name' => 'AZERBAÏDJAN', 'nationality' => 'Azerbaïdjanaise', 'iso_code_2' => 'AZ', 'iso_code_3' => 'AZE', 'phone_code' => '994', 'continent' => 'AS', 'is_active' => true],
            ['id' => 32, 'name' => 'ARGENTINE', 'nationality' => 'Argentine', 'iso_code_2' => 'AR', 'iso_code_3' => 'ARG', 'phone_code' => '54', 'continent' => 'SA', 'is_active' => true],
            ['id' => 36, 'name' => 'AUSTRALIE', 'nationality' => 'Australienne', 'iso_code_2' => 'AU', 'iso_code_3' => 'AUS', 'phone_code' => '61', 'continent' => 'OC', 'is_active' => true],
            ['id' => 40, 'name' => 'AUTRICHE', 'nationality' => 'Autrichienne', 'iso_code_2' => 'AT', 'iso_code_3' => 'AUT', 'phone_code' => '43', 'continent' => 'EU', 'is_active' => true],
            ['id' => 44, 'name' => 'BAHAMAS (LES)', 'nationality' => 'Bahamienne', 'iso_code_2' => 'BS', 'iso_code_3' => 'BHS', 'phone_code' => '1242', 'continent' => 'NA', 'is_active' => true],
            ['id' => 48, 'name' => 'BAHREÏN', 'nationality' => 'Bahreïnienne', 'iso_code_2' => 'BH', 'iso_code_3' => 'BHR', 'phone_code' => '973', 'continent' => 'AS', 'is_active' => true],
            ['id' => 50, 'name' => 'BANGLADESH', 'nationality' => 'Bangladaise', 'iso_code_2' => 'BD', 'iso_code_3' => 'BGD', 'phone_code' => '880', 'continent' => 'AS', 'is_active' => true],
            ['id' => 51, 'name' => 'ARMÉNIE', 'nationality' => 'Arménienne', 'iso_code_2' => 'AM', 'iso_code_3' => 'ARM', 'phone_code' => '374', 'continent' => 'AS', 'is_active' => true],
            ['id' => 52, 'name' => 'BARBADE', 'nationality' => 'Barbadienne', 'iso_code_2' => 'BB', 'iso_code_3' => 'BRB', 'phone_code' => '1246', 'continent' => 'NA', 'is_active' => true],
            ['id' => 56, 'name' => 'BELGIQUE', 'nationality' => 'Belge', 'iso_code_2' => 'BE', 'iso_code_3' => 'BEL', 'phone_code' => '32', 'continent' => 'EU', 'is_active' => true],
            ['id' => 60, 'name' => 'BERMUDES', 'nationality' => 'Bermudienne', 'iso_code_2' => 'BM', 'iso_code_3' => 'BMU', 'phone_code' => '1441', 'continent' => 'NA', 'is_active' => true],
            ['id' => 64, 'name' => 'BHOUTAN', 'nationality' => 'Bhoutanaise', 'iso_code_2' => 'BT', 'iso_code_3' => 'BTN', 'phone_code' => '975', 'continent' => 'AS', 'is_active' => true],
            ['id' => 68, 'name' => 'BOLIVIE (ÉTAT PLURINATIONAL DE)', 'nationality' => 'Bolivienne', 'iso_code_2' => 'BO', 'iso_code_3' => 'BOL', 'phone_code' => '591', 'continent' => 'SA', 'is_active' => true],
            ['id' => 70, 'name' => 'BOSNIE-HERZÉGOVINE', 'nationality' => 'Bosnienne', 'iso_code_2' => 'BA', 'iso_code_3' => 'BIH', 'phone_code' => '387', 'continent' => 'EU', 'is_active' => true],
            ['id' => 72, 'name' => 'BOTSWANA', 'nationality' => 'Botswanaise', 'iso_code_2' => 'BW', 'iso_code_3' => 'BWA', 'phone_code' => '267', 'continent' => 'AF', 'is_active' => true],
            ['id' => 76, 'name' => 'BRÉSIL', 'nationality' => 'Brésilienne', 'iso_code_2' => 'BR', 'iso_code_3' => 'BRA', 'phone_code' => '55', 'continent' => 'SA', 'is_active' => true],
            ['id' => 84, 'name' => 'BELIZE', 'nationality' => 'Bélizienne', 'iso_code_2' => 'BZ', 'iso_code_3' => 'BLZ', 'phone_code' => '501', 'continent' => 'NA', 'is_active' => true],
            ['id' => 86, 'name' => "TERRITOIRE BRITANNIQUE DE L'OCÉAN INDIEN (LE)", 'nationality' => 'Britannique', 'iso_code_2' => 'IO', 'iso_code_3' => 'IOT', 'phone_code' => '246', 'continent' => 'AS', 'is_active' => true],
            ['id' => 90, 'name' => 'ÎLES SOLOMON', 'nationality' => 'Salomonienne', 'iso_code_2' => 'SB', 'iso_code_3' => 'SLB', 'phone_code' => '677', 'continent' => 'OC', 'is_active' => true],
            ['id' => 92, 'name' => 'ÎLES VIERGES (BRITANNIQUES)', 'nationality' => 'Viergoise britannique', 'iso_code_2' => 'VG', 'iso_code_3' => 'VGB', 'phone_code' => '1284', 'continent' => 'NA', 'is_active' => true],
            ['id' => 96, 'name' => 'BRUNÉI DARUSSALAM', 'nationality' => 'Brunéienne', 'iso_code_2' => 'BN', 'iso_code_3' => 'BRN', 'phone_code' => '673', 'continent' => 'AS', 'is_active' => true],
            ['id' => 100, 'name' => 'BULGARIE', 'nationality' => 'Bulgare', 'iso_code_2' => 'BG', 'iso_code_3' => 'BGR', 'phone_code' => '359', 'continent' => 'EU', 'is_active' => true],
            ['id' => 104, 'name' => 'MYANMAR', 'nationality' => 'Birmane', 'iso_code_2' => 'MM', 'iso_code_3' => 'MMR', 'phone_code' => '95', 'continent' => 'AS', 'is_active' => true],
            ['id' => 108, 'name' => 'BURUNDI', 'nationality' => 'Burundaise', 'iso_code_2' => 'BI', 'iso_code_3' => 'BDI', 'phone_code' => '257', 'continent' => 'AF', 'is_active' => true],
            ['id' => 112, 'name' => 'BÉLARUS', 'nationality' => 'Bélarusse', 'iso_code_2' => 'BY', 'iso_code_3' => 'BLR', 'phone_code' => '375', 'continent' => 'EU', 'is_active' => true],
            ['id' => 116, 'name' => 'CAMBODGE', 'nationality' => 'Cambodgienne', 'iso_code_2' => 'KH', 'iso_code_3' => 'KHM', 'phone_code' => '855', 'continent' => 'AS', 'is_active' => true],
            ['id' => 120, 'name' => 'CAMEROUN', 'nationality' => 'Camerounaise', 'iso_code_2' => 'CM', 'iso_code_3' => 'CMR', 'phone_code' => '237', 'continent' => 'AF', 'is_active' => true],
            ['id' => 124, 'name' => 'CANADA', 'nationality' => 'Canadienne', 'iso_code_2' => 'CA', 'iso_code_3' => 'CAN', 'phone_code' => '1', 'continent' => 'NA', 'is_active' => true],
            ['id' => 132, 'name' => 'CAP-VERT', 'nationality' => 'Cap-verdienne', 'iso_code_2' => 'CV', 'iso_code_3' => 'CPV', 'phone_code' => '238', 'continent' => 'AF', 'is_active' => true],
            ['id' => 136, 'name' => 'ÎLES CAÏMANS (LES)', 'nationality' => 'Caïmanienne', 'iso_code_2' => 'KY', 'iso_code_3' => 'CYM', 'phone_code' => '1345', 'continent' => 'NA', 'is_active' => true],
            ['id' => 140, 'name' => 'RÉPUBLIQUE CENTRAFRICAINE (LA)', 'nationality' => 'Centrafricaine', 'iso_code_2' => 'CF', 'iso_code_3' => 'CAF', 'phone_code' => '236', 'continent' => 'AF', 'is_active' => true],
            ['id' => 144, 'name' => 'SRI LANKA', 'nationality' => 'Sri-Lankaise', 'iso_code_2' => 'LK', 'iso_code_3' => 'LKA', 'phone_code' => '94', 'continent' => 'AS', 'is_active' => true],
            ['id' => 148, 'name' => 'TCHAD', 'nationality' => 'Tchadienne', 'iso_code_2' => 'TD', 'iso_code_3' => 'TCD', 'phone_code' => '235', 'continent' => 'AF', 'is_active' => true],
            ['id' => 152, 'name' => 'CHILI', 'nationality' => 'Chilienne', 'iso_code_2' => 'CL', 'iso_code_3' => 'CHL', 'phone_code' => '56', 'continent' => 'SA', 'is_active' => true],
            ['id' => 153, 'name' => 'KOSOVO', 'nationality' => 'Kosovarde', 'iso_code_2' => 'XK', 'iso_code_3' => 'XKX', 'phone_code' => '383', 'continent' => 'EU', 'is_active' => true],
            ['id' => 156, 'name' => 'CHINE', 'nationality' => 'Chinoise', 'iso_code_2' => 'CN', 'iso_code_3' => 'CHN', 'phone_code' => '86', 'continent' => 'AS', 'is_active' => true],
            ['id' => 158, 'name' => 'TAÏWAN', 'nationality' => 'Taïwanaise', 'iso_code_2' => 'TW', 'iso_code_3' => 'TWN', 'phone_code' => '886', 'continent' => 'AS', 'is_active' => true],
            ['id' => 162, 'name' => 'ÎLE CHRISTMAS', 'nationality' => 'Australienne', 'iso_code_2' => 'CX', 'iso_code_3' => 'CXR', 'phone_code' => '61', 'continent' => 'OC', 'is_active' => true],
            ['id' => 166, 'name' => 'ÎLES COCOS (KEELING)', 'nationality' => 'Australienne', 'iso_code_2' => 'CC', 'iso_code_3' => 'CCK', 'phone_code' => '61', 'continent' => 'AS', 'is_active' => true],
            ['id' => 170, 'name' => 'COLOMBIE', 'nationality' => 'Colombienne', 'iso_code_2' => 'CO', 'iso_code_3' => 'COL', 'phone_code' => '57', 'continent' => 'SA', 'is_active' => true],
            ['id' => 174, 'name' => 'COMORES', 'nationality' => 'Comorienne', 'iso_code_2' => 'KM', 'iso_code_3' => 'COM', 'phone_code' => '269', 'continent' => 'AF', 'is_active' => true],
            ['id' => 175, 'name' => 'MAYOTTE', 'nationality' => 'Française', 'iso_code_2' => 'YT', 'iso_code_3' => 'MYT', 'phone_code' => '269', 'continent' => 'AF', 'is_active' => true],
            ['id' => 178, 'name' => 'CONGO', 'nationality' => 'Congolaise', 'iso_code_2' => 'CG', 'iso_code_3' => 'COG', 'phone_code' => '242', 'continent' => 'AF', 'is_active' => true],
            ['id' => 180, 'name' => 'RÉPUBLIQUE DÉMOCRATIQUE DU CONGO', 'nationality' => 'Congolaise', 'iso_code_2' => 'CD', 'iso_code_3' => 'COD', 'phone_code' => '243', 'continent' => 'AF', 'is_active' => true],
            ['id' => 184, 'name' => 'ÎLES COOK', 'nationality' => 'Néo-Zélandaise', 'iso_code_2' => 'CK', 'iso_code_3' => 'COK', 'phone_code' => '682', 'continent' => 'OC', 'is_active' => true],
            ['id' => 188, 'name' => 'COSTA RICA', 'nationality' => 'Costaricienne', 'iso_code_2' => 'CR', 'iso_code_3' => 'CRI', 'phone_code' => '506', 'continent' => 'NA', 'is_active' => true],
            ['id' => 191, 'name' => 'CROATIE', 'nationality' => 'Croate', 'iso_code_2' => 'HR', 'iso_code_3' => 'HRV', 'phone_code' => '385', 'continent' => 'EU', 'is_active' => true],
            ['id' => 192, 'name' => 'CUBA', 'nationality' => 'Cubaine', 'iso_code_2' => 'CU', 'iso_code_3' => 'CUB', 'phone_code' => '53', 'continent' => 'NA', 'is_active' => true],
            ['id' => 196, 'name' => 'CHYPRE', 'nationality' => 'Chypriote', 'iso_code_2' => 'CY', 'iso_code_3' => 'CYP', 'phone_code' => '357', 'continent' => 'EU', 'is_active' => true],
            ['id' => 203, 'name' => 'TCHÉQUIE', 'nationality' => 'Tchèque', 'iso_code_2' => 'CZ', 'iso_code_3' => 'CZE', 'phone_code' => '420', 'continent' => 'EU', 'is_active' => true],
            ['id' => 204, 'name' => 'BÉNIN', 'nationality' => 'Béninoise', 'iso_code_2' => 'BJ', 'iso_code_3' => 'BEN', 'phone_code' => '229', 'continent' => 'AF', 'is_active' => true],
            ['id' => 208, 'name' => 'DANEMARK', 'nationality' => 'Danoise', 'iso_code_2' => 'DK', 'iso_code_3' => 'DNK', 'phone_code' => '45', 'continent' => 'EU', 'is_active' => true],
            ['id' => 212, 'name' => 'DOMINIQUE', 'nationality' => 'Dominiquaise', 'iso_code_2' => 'DM', 'iso_code_3' => 'DMA', 'phone_code' => '1767', 'continent' => 'NA', 'is_active' => true],
            ['id' => 214, 'name' => 'RÉPUBLIQUE DOMINICAINE', 'nationality' => 'Dominicaine', 'iso_code_2' => 'DO', 'iso_code_3' => 'DOM', 'phone_code' => '1809', 'continent' => 'NA', 'is_active' => true],
            ['id' => 218, 'name' => 'ÉQUATEUR', 'nationality' => 'Équatorienne', 'iso_code_2' => 'EC', 'iso_code_3' => 'ECU', 'phone_code' => '593', 'continent' => 'SA', 'is_active' => true],
            ['id' => 222, 'name' => 'EL SALVADOR', 'nationality' => 'Salvadorienne', 'iso_code_2' => 'SV', 'iso_code_3' => 'SLV', 'phone_code' => '503', 'continent' => 'NA', 'is_active' => true],
            ['id' => 226, 'name' => 'GUINÉE ÉQUATORIALE', 'nationality' => 'Équatoguinéenne', 'iso_code_2' => 'GQ', 'iso_code_3' => 'GNQ', 'phone_code' => '240', 'continent' => 'AF', 'is_active' => true],
            ['id' => 231, 'name' => 'ÉTHIOPIE', 'nationality' => 'Éthiopienne', 'iso_code_2' => 'ET', 'iso_code_3' => 'ETH', 'phone_code' => '251', 'continent' => 'AF', 'is_active' => true],
            ['id' => 232, 'name' => 'ÉRYTHRÉE', 'nationality' => 'Érythréenne', 'iso_code_2' => 'ER', 'iso_code_3' => 'ERI', 'phone_code' => '291', 'continent' => 'AF', 'is_active' => true],
            ['id' => 233, 'name' => 'ESTONIE', 'nationality' => 'Estonienne', 'iso_code_2' => 'EE', 'iso_code_3' => 'EST', 'phone_code' => '372', 'continent' => 'EU', 'is_active' => true],
            ['id' => 234, 'name' => 'ÎLES FÉROÉ', 'nationality' => 'Féroïenne', 'iso_code_2' => 'FO', 'iso_code_3' => 'FRO', 'phone_code' => '298', 'continent' => 'EU', 'is_active' => true],
            ['id' => 238, 'name' => 'ÎLES MALOUINES', 'nationality' => 'Falklandaise', 'iso_code_2' => 'FK', 'iso_code_3' => 'FLK', 'phone_code' => '500', 'continent' => 'SA', 'is_active' => true],
            ['id' => 239, 'name' => 'GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD', 'nationality' => 'Britannique', 'iso_code_2' => 'GS', 'iso_code_3' => 'SGS', 'phone_code' => '500', 'continent' => 'AN', 'is_active' => true],
            ['id' => 242, 'name' => 'FIDJI', 'nationality' => 'Fidjienne', 'iso_code_2' => 'FJ', 'iso_code_3' => 'FJI', 'phone_code' => '679', 'continent' => 'OC', 'is_active' => true],
            ['id' => 246, 'name' => 'FINLANDE', 'nationality' => 'Finlandaise', 'iso_code_2' => 'FI', 'iso_code_3' => 'FIN', 'phone_code' => '358', 'continent' => 'EU', 'is_active' => true],
            ['id' => 250, 'name' => 'FRANCE', 'nationality' => 'Française', 'iso_code_2' => 'FR', 'iso_code_3' => 'FRA', 'phone_code' => '33', 'continent' => 'EU', 'is_active' => true],
            ['id' => 254, 'name' => 'GUYANE FRANÇAISE', 'nationality' => 'Française', 'iso_code_2' => 'GF', 'iso_code_3' => 'GUF', 'phone_code' => '594', 'continent' => 'SA', 'is_active' => true],
            ['id' => 258, 'name' => 'POLYNÉSIE FRANÇAISE', 'nationality' => 'Française', 'iso_code_2' => 'PF', 'iso_code_3' => 'PYF', 'phone_code' => '689', 'continent' => 'OC', 'is_active' => true],
            ['id' => 260, 'name' => 'TERRES AUSTRALES ET ANTARCTIQUES FRANÇAISES', 'nationality' => 'Française', 'iso_code_2' => 'TF', 'iso_code_3' => 'ATF', 'phone_code' => '262', 'continent' => 'AN', 'is_active' => true],
            ['id' => 262, 'name' => 'DJIBOUTI', 'nationality' => 'Djiboutienne', 'iso_code_2' => 'DJ', 'iso_code_3' => 'DJI', 'phone_code' => '253', 'continent' => 'AF', 'is_active' => true],
            ['id' => 266, 'name' => 'GABON', 'nationality' => 'Gabonaise', 'iso_code_2' => 'GA', 'iso_code_3' => 'GAB', 'phone_code' => '241', 'continent' => 'AF', 'is_active' => true],
            ['id' => 268, 'name' => 'GÉORGIE', 'nationality' => 'Géorgienne', 'iso_code_2' => 'GE', 'iso_code_3' => 'GEO', 'phone_code' => '995', 'continent' => 'AS', 'is_active' => true],
            ['id' => 270, 'name' => 'GAMBIE', 'nationality' => 'Gambienne', 'iso_code_2' => 'GM', 'iso_code_3' => 'GMB', 'phone_code' => '220', 'continent' => 'AF', 'is_active' => true],
            ['id' => 275, 'name' => 'PALESTINE', 'nationality' => 'Palestinienne', 'iso_code_2' => 'PS', 'iso_code_3' => 'PSE', 'phone_code' => '970', 'continent' => 'AS', 'is_active' => true],
            ['id' => 276, 'name' => 'ALLEMAGNE', 'nationality' => 'Allemande', 'iso_code_2' => 'DE', 'iso_code_3' => 'DEU', 'phone_code' => '49', 'continent' => 'EU', 'is_active' => true],
            ['id' => 288, 'name' => 'GHANA', 'nationality' => 'Ghanéenne', 'iso_code_2' => 'GH', 'iso_code_3' => 'GHA', 'phone_code' => '233', 'continent' => 'AF', 'is_active' => true],
            ['id' => 292, 'name' => 'GIBRALTAR', 'nationality' => 'Gibraltarienne', 'iso_code_2' => 'GI', 'iso_code_3' => 'GIB', 'phone_code' => '350', 'continent' => 'EU', 'is_active' => true],
            ['id' => 296, 'name' => 'KIRIBATI', 'nationality' => 'Kiribatienne', 'iso_code_2' => 'KI', 'iso_code_3' => 'KIR', 'phone_code' => '686', 'continent' => 'OC', 'is_active' => true],
            ['id' => 300, 'name' => 'GRÈCE', 'nationality' => 'Grecque', 'iso_code_2' => 'GR', 'iso_code_3' => 'GRC', 'phone_code' => '30', 'continent' => 'EU', 'is_active' => true],
            ['id' => 304, 'name' => 'GROENLAND', 'nationality' => 'Groenlandaise', 'iso_code_2' => 'GL', 'iso_code_3' => 'GRL', 'phone_code' => '299', 'continent' => 'NA', 'is_active' => true],
            ['id' => 308, 'name' => 'GRENADE', 'nationality' => 'Grenadienne', 'iso_code_2' => 'GD', 'iso_code_3' => 'GRD', 'phone_code' => '1473', 'continent' => 'NA', 'is_active' => true],
            ['id' => 312, 'name' => 'GUADELOUPE', 'nationality' => 'Française', 'iso_code_2' => 'GP', 'iso_code_3' => 'GLP', 'phone_code' => '590', 'continent' => 'NA', 'is_active' => true],
            ['id' => 316, 'name' => 'GUAM', 'nationality' => 'Américaine', 'iso_code_2' => 'GU', 'iso_code_3' => 'GUM', 'phone_code' => '671', 'continent' => 'OC', 'is_active' => true],
            ['id' => 320, 'name' => 'GUATEMALA', 'nationality' => 'Guatémaltèque', 'iso_code_2' => 'GT', 'iso_code_3' => 'GTM', 'phone_code' => '502', 'continent' => 'NA', 'is_active' => true],
            ['id' => 324, 'name' => 'GUINÉE', 'nationality' => 'Guinéenne', 'iso_code_2' => 'GN', 'iso_code_3' => 'GIN', 'phone_code' => '224', 'continent' => 'AF', 'is_active' => true],
            ['id' => 328, 'name' => 'GUYANA', 'nationality' => 'Guyanienne', 'iso_code_2' => 'GY', 'iso_code_3' => 'GUY', 'phone_code' => '592', 'continent' => 'SA', 'is_active' => true],
            ['id' => 332, 'name' => 'HAÏTI', 'nationality' => 'Haïtienne', 'iso_code_2' => 'HT', 'iso_code_3' => 'HTI', 'phone_code' => '509', 'continent' => 'NA', 'is_active' => true],
            ['id' => 336, 'name' => 'SAINT-SIÈGE (VATIKAN)', 'nationality' => 'Vaticane', 'iso_code_2' => 'VA', 'iso_code_3' => 'VAT', 'phone_code' => '39', 'continent' => 'EU', 'is_active' => true],
            ['id' => 340, 'name' => 'HONDURAS', 'nationality' => 'Hondurienne', 'iso_code_2' => 'HN', 'iso_code_3' => 'HND', 'phone_code' => '504', 'continent' => 'NA', 'is_active' => true],
            ['id' => 344, 'name' => 'HONG KONG', 'nationality' => 'Hongkongaise', 'iso_code_2' => 'HK', 'iso_code_3' => 'HKG', 'phone_code' => '852', 'continent' => 'AS', 'is_active' => true],
            ['id' => 348, 'name' => 'HONGRIE', 'nationality' => 'Hongroise', 'iso_code_2' => 'HU', 'iso_code_3' => 'HUN', 'phone_code' => '36', 'continent' => 'EU', 'is_active' => true],
            ['id' => 352, 'name' => 'ISLANDE', 'nationality' => 'Islandaise', 'iso_code_2' => 'IS', 'iso_code_3' => 'ISL', 'phone_code' => '354', 'continent' => 'EU', 'is_active' => true],
            ['id' => 356, 'name' => 'INDE', 'nationality' => 'Indienne', 'iso_code_2' => 'IN', 'iso_code_3' => 'IND', 'phone_code' => '91', 'continent' => 'AS', 'is_active' => true],
            ['id' => 360, 'name' => 'INDONÉSIE', 'nationality' => 'Indonésienne', 'iso_code_2' => 'ID', 'iso_code_3' => 'IDN', 'phone_code' => '62', 'continent' => 'AS', 'is_active' => true],
            ['id' => 364, 'name' => 'IRAN', 'nationality' => 'Iranienne', 'iso_code_2' => 'IR', 'iso_code_3' => 'IRN', 'phone_code' => '98', 'continent' => 'AS', 'is_active' => true],
            ['id' => 368, 'name' => 'IRAQ', 'nationality' => 'Irakienne', 'iso_code_2' => 'IQ', 'iso_code_3' => 'IRQ', 'phone_code' => '964', 'continent' => 'AS', 'is_active' => true],
            ['id' => 372, 'name' => 'IRLANDE', 'nationality' => 'Irlandaise', 'iso_code_2' => 'IE', 'iso_code_3' => 'IRL', 'phone_code' => '353', 'continent' => 'EU', 'is_active' => true],
            ['id' => 376, 'name' => 'ISRAËL', 'nationality' => 'Israélienne', 'iso_code_2' => 'IL', 'iso_code_3' => 'ISR', 'phone_code' => '972', 'continent' => 'AS', 'is_active' => true],
            ['id' => 380, 'name' => 'ITALIE', 'nationality' => 'Italienne', 'iso_code_2' => 'IT', 'iso_code_3' => 'ITA', 'phone_code' => '390', 'continent' => 'EU', 'is_active' => true],
            ['id' => 384, 'name' => "CÔTE D'IVOIRE", 'nationality' => 'Ivoirienne', 'iso_code_2' => 'CI', 'iso_code_3' => 'CIV', 'phone_code' => '225', 'continent' => 'AF', 'is_active' => true],
            ['id' => 388, 'name' => 'JAMAÏQUE', 'nationality' => 'Jamaïcaine', 'iso_code_2' => 'JM', 'iso_code_3' => 'JAM', 'phone_code' => '1876', 'continent' => 'NA', 'is_active' => true],
            ['id' => 392, 'name' => 'JAPON', 'nationality' => 'Japonaise', 'iso_code_2' => 'JP', 'iso_code_3' => 'JPN', 'phone_code' => '81', 'continent' => 'AS', 'is_active' => true],
            ['id' => 398, 'name' => 'KAZAKHSTAN', 'nationality' => 'Kazakhstanaise', 'iso_code_2' => 'KZ', 'iso_code_3' => 'KAZ', 'phone_code' => '7', 'continent' => 'AS', 'is_active' => true],
            ['id' => 400, 'name' => 'JORDANIE', 'nationality' => 'Jordonienne', 'iso_code_2' => 'JO', 'iso_code_3' => 'JOR', 'phone_code' => '962', 'continent' => 'AS', 'is_active' => true],
            ['id' => 404, 'name' => 'KENYA', 'nationality' => 'Kényane', 'iso_code_2' => 'KE', 'iso_code_3' => 'KEN', 'phone_code' => '254', 'continent' => 'AF', 'is_active' => true],
            ['id' => 408, 'name' => 'CORÉE DU NORD', 'nationality' => 'Nord-Coréenne', 'iso_code_2' => 'KP', 'iso_code_3' => 'PRK', 'phone_code' => '850', 'continent' => 'AS', 'is_active' => true],
            ['id' => 410, 'name' => 'CORÉE DU SUD', 'nationality' => 'Sud-Coréenne', 'iso_code_2' => 'KR', 'iso_code_3' => 'KOR', 'phone_code' => '82', 'continent' => 'AS', 'is_active' => true],
            ['id' => 414, 'name' => 'KOWEÏT', 'nationality' => 'Koweïtienne', 'iso_code_2' => 'KW', 'iso_code_3' => 'KWT', 'phone_code' => '965', 'continent' => 'AS', 'is_active' => true],
            ['id' => 417, 'name' => 'KIRGHIZISTAN', 'nationality' => 'Kirghize', 'iso_code_2' => 'KG', 'iso_code_3' => 'KGZ', 'phone_code' => '996', 'continent' => 'AS', 'is_active' => true],
            ['id' => 418, 'name' => 'LAOS', 'nationality' => 'Laotienne', 'iso_code_2' => 'LA', 'iso_code_3' => 'LAO', 'phone_code' => '856', 'continent' => 'AS', 'is_active' => true],
            ['id' => 422, 'name' => 'LIBAN', 'nationality' => 'Libanaise', 'iso_code_2' => 'LB', 'iso_code_3' => 'LBN', 'phone_code' => '961', 'continent' => 'AS', 'is_active' => true],
            ['id' => 426, 'name' => 'LESOTHO', 'nationality' => 'Lésothane', 'iso_code_2' => 'LS', 'iso_code_3' => 'LSO', 'phone_code' => '266', 'continent' => 'AF', 'is_active' => true],
            ['id' => 428, 'name' => 'LETTONIE', 'nationality' => 'Lettonne', 'iso_code_2' => 'LV', 'iso_code_3' => 'LVA', 'phone_code' => '371', 'continent' => 'EU', 'is_active' => true],
            ['id' => 430, 'name' => 'LIBÉRIA', 'nationality' => 'Libérienne', 'iso_code_2' => 'LR', 'iso_code_3' => 'LBR', 'phone_code' => '231', 'continent' => 'AF', 'is_active' => true],
            ['id' => 434, 'name' => 'LIBYE', 'nationality' => 'Libyenne', 'iso_code_2' => 'LY', 'iso_code_3' => 'LBY', 'phone_code' => '218', 'continent' => 'AF', 'is_active' => true],
            ['id' => 438, 'name' => 'LIECHTENSTEIN', 'nationality' => 'Liechtensteinoise', 'iso_code_2' => 'LI', 'iso_code_3' => 'LIE', 'phone_code' => '423', 'continent' => 'EU', 'is_active' => true],
            ['id' => 440, 'name' => 'LITUANIE', 'nationality' => 'Lituanienne', 'iso_code_2' => 'LT', 'iso_code_3' => 'LTU', 'phone_code' => '370', 'continent' => 'EU', 'is_active' => true],
            ['id' => 442, 'name' => 'LUXEMBOURG', 'nationality' => 'Luxembourgeoise', 'iso_code_2' => 'LU', 'iso_code_3' => 'LUX', 'phone_code' => '352', 'continent' => 'EU', 'is_active' => true],
            ['id' => 446, 'name' => 'MACAO', 'nationality' => 'Macanaise', 'iso_code_2' => 'MO', 'iso_code_3' => 'MAC', 'phone_code' => '853', 'continent' => 'AS', 'is_active' => true],
            ['id' => 450, 'name' => 'MADAGASCAR', 'nationality' => 'Malagasy', 'iso_code_2' => 'MG', 'iso_code_3' => 'MDG', 'phone_code' => '261', 'continent' => 'AF', 'is_active' => true],
            ['id' => 454, 'name' => 'MALAWI', 'nationality' => 'Malawienne', 'iso_code_2' => 'MW', 'iso_code_3' => 'MWI', 'phone_code' => '265', 'continent' => 'AF', 'is_active' => true],
            ['id' => 458, 'name' => 'MALAISIE', 'nationality' => 'Malaisienne', 'iso_code_2' => 'MY', 'iso_code_3' => 'MYS', 'phone_code' => '60', 'continent' => 'AS', 'is_active' => true],
            ['id' => 462, 'name' => 'MALDIVES', 'nationality' => 'Maldivienne', 'iso_code_2' => 'MV', 'iso_code_3' => 'MDV', 'phone_code' => '960', 'continent' => 'AS', 'is_active' => true],
            ['id' => 466, 'name' => 'MALI', 'nationality' => 'Malienne', 'iso_code_2' => 'ML', 'iso_code_3' => 'MLI', 'phone_code' => '223', 'continent' => 'AF', 'is_active' => true],
            ['id' => 470, 'name' => 'MALTE', 'nationality' => 'Maltaise', 'iso_code_2' => 'MT', 'iso_code_3' => 'MLT', 'phone_code' => '356', 'continent' => 'EU', 'is_active' => true],
            ['id' => 474, 'name' => 'MARTINIQUE', 'nationality' => 'Française', 'iso_code_2' => 'MQ', 'iso_code_3' => 'MTQ', 'phone_code' => '596', 'continent' => 'NA', 'is_active' => true],
            ['id' => 478, 'name' => 'MAURITANIE', 'nationality' => 'Mauritanienne', 'iso_code_2' => 'MR', 'iso_code_3' => 'MRT', 'phone_code' => '222', 'continent' => 'AF', 'is_active' => true],
            ['id' => 480, 'name' => 'MAURICE', 'nationality' => 'Mauricienne', 'iso_code_2' => 'MU', 'iso_code_3' => 'MUS', 'phone_code' => '230', 'continent' => 'AF', 'is_active' => true],
            ['id' => 484, 'name' => 'MEXIQUE', 'nationality' => 'Mexicaine', 'iso_code_2' => 'MX', 'iso_code_3' => 'MEX', 'phone_code' => '52', 'continent' => 'NA', 'is_active' => true],
            ['id' => 492, 'name' => 'MONACO', 'nationality' => 'Monégasque', 'iso_code_2' => 'MC', 'iso_code_3' => 'MCO', 'phone_code' => '377', 'continent' => 'EU', 'is_active' => true],
            ['id' => 496, 'name' => 'MONGOLIE', 'nationality' => 'Mongole', 'iso_code_2' => 'MN', 'iso_code_3' => 'MNG', 'phone_code' => '976', 'continent' => 'AS', 'is_active' => true],
            ['id' => 498, 'name' => 'MOLDOVA', 'nationality' => 'Moldave', 'iso_code_2' => 'MD', 'iso_code_3' => 'MDA', 'phone_code' => '373', 'continent' => 'EU', 'is_active' => true],
            ['id' => 499, 'name' => 'MONTÉNÉGRO', 'nationality' => 'Monténégrine', 'iso_code_2' => 'ME', 'iso_code_3' => 'MNE', 'phone_code' => '382', 'continent' => 'EU', 'is_active' => true],
            ['id' => 500, 'name' => 'MONTSERRAT', 'nationality' => 'Britannique', 'iso_code_2' => 'MS', 'iso_code_3' => 'MSR', 'phone_code' => '1664', 'continent' => 'NA', 'is_active' => true],
            ['id' => 504, 'name' => 'MAROC', 'nationality' => 'Marocaine', 'iso_code_2' => 'MA', 'iso_code_3' => 'MAR', 'phone_code' => '212', 'continent' => 'AF', 'is_active' => true],
            ['id' => 508, 'name' => 'MOZAMBIQUE', 'nationality' => 'Mozambicaine', 'iso_code_2' => 'MZ', 'iso_code_3' => 'MOZ', 'phone_code' => '258', 'continent' => 'AF', 'is_active' => true],
            ['id' => 512, 'name' => 'OMAN', 'nationality' => 'Omanaise', 'iso_code_2' => 'OM', 'iso_code_3' => 'OMN', 'phone_code' => '968', 'continent' => 'AS', 'is_active' => true],
            ['id' => 516, 'name' => 'NAMIBIE', 'nationality' => 'Namibienne', 'iso_code_2' => 'NA', 'iso_code_3' => 'NAM', 'phone_code' => '264', 'continent' => 'AF', 'is_active' => true],
            ['id' => 520, 'name' => 'NAURU', 'nationality' => 'Nauruane', 'iso_code_2' => 'NR', 'iso_code_3' => 'NRU', 'phone_code' => '674', 'continent' => 'OC', 'is_active' => true],
            ['id' => 524, 'name' => 'NÉPAL', 'nationality' => 'Népalaise', 'iso_code_2' => 'NP', 'iso_code_3' => 'NPL', 'phone_code' => '977', 'continent' => 'AS', 'is_active' => true],
            ['id' => 528, 'name' => 'PAYS-BAS', 'nationality' => 'Néerlandaise', 'iso_code_2' => 'NL', 'iso_code_3' => 'NLD', 'phone_code' => '31', 'continent' => 'EU', 'is_active' => true],
            ['id' => 531, 'name' => 'CURAÇAO', 'nationality' => 'Néerlandaise', 'iso_code_2' => 'CW', 'iso_code_3' => 'CUW', 'phone_code' => '599', 'continent' => 'NA', 'is_active' => true],
            ['id' => 533, 'name' => 'ARUBA', 'nationality' => 'Néerlandaise', 'iso_code_2' => 'AW', 'iso_code_3' => 'ABW', 'phone_code' => '297', 'continent' => 'NA', 'is_active' => true],
            ['id' => 534, 'name' => 'SAINT-MARTIN (PARTIE NÉERLANDAISE)', 'nationality' => 'Néerlandaise', 'iso_code_2' => 'SX', 'iso_code_3' => 'SXM', 'phone_code' => '721', 'continent' => 'NA', 'is_active' => true],
            ['id' => 535, 'name' => 'PAYS-BAS CARIBÉENS', 'nationality' => 'Néerlandaise', 'iso_code_2' => 'BQ', 'iso_code_3' => 'BES', 'phone_code' => '599', 'continent' => 'NA', 'is_active' => true],
            ['id' => 540, 'name' => 'NOUVELLE-CALÉDONIE', 'nationality' => 'Française', 'iso_code_2' => 'NC', 'iso_code_3' => 'NCL', 'phone_code' => '687', 'continent' => 'OC', 'is_active' => true],
            ['id' => 548, 'name' => 'VANUATU', 'nationality' => 'Vanuatause', 'iso_code_2' => 'VU', 'iso_code_3' => 'VUT', 'phone_code' => '678', 'continent' => 'OC', 'is_active' => true],
            ['id' => 554, 'name' => 'NOUVELLE-ZÉLANDE', 'nationality' => 'Néo-Zélandaise', 'iso_code_2' => 'NZ', 'iso_code_3' => 'NZL', 'phone_code' => '64', 'continent' => 'OC', 'is_active' => true],
            ['id' => 558, 'name' => 'NICARAGUA', 'nationality' => 'Nicaraguayenne', 'iso_code_2' => 'NI', 'iso_code_3' => 'NIC', 'phone_code' => '505', 'continent' => 'NA', 'is_active' => true],
            ['id' => 562, 'name' => 'NIGER', 'nationality' => 'Nigérienne', 'iso_code_2' => 'NE', 'iso_code_3' => 'NER', 'phone_code' => '227', 'continent' => 'AF', 'is_active' => true],
            ['id' => 566, 'name' => 'NIGÉRIA', 'nationality' => 'Nigériane', 'iso_code_2' => 'NG', 'iso_code_3' => 'NGA', 'phone_code' => '234', 'continent' => 'AF', 'is_active' => true],
            ['id' => 570, 'name' => 'NIUÉ', 'nationality' => 'Néo-Zélandaise', 'iso_code_2' => 'NU', 'iso_code_3' => 'NIU', 'phone_code' => '683', 'continent' => 'OC', 'is_active' => true],
            ['id' => 574, 'name' => 'ÎLE NORFOLK', 'nationality' => 'Australienne', 'iso_code_2' => 'NF', 'iso_code_3' => 'NFK', 'phone_code' => '672', 'continent' => 'OC', 'is_active' => true],
            ['id' => 578, 'name' => 'NORVÈGE', 'nationality' => 'Norvégienne', 'iso_code_2' => 'NO', 'iso_code_3' => 'NOR', 'phone_code' => '47', 'continent' => 'EU', 'is_active' => true],
            ['id' => 580, 'name' => 'ÎLES MARIANNES DU NORD', 'nationality' => 'Américaine', 'iso_code_2' => 'MP', 'iso_code_3' => 'MNP', 'phone_code' => '1670', 'continent' => 'OC', 'is_active' => true],
            ['id' => 583, 'name' => 'MICRONÉSIE', 'nationality' => 'Micronésienne', 'iso_code_2' => 'FM', 'iso_code_3' => 'FSM', 'phone_code' => '691', 'continent' => 'OC', 'is_active' => true],
            ['id' => 584, 'name' => 'ÎLES MARSHALL', 'nationality' => 'Marshallaise', 'iso_code_2' => 'MH', 'iso_code_3' => 'MHL', 'phone_code' => '692', 'continent' => 'OC', 'is_active' => true],
            ['id' => 585, 'name' => 'PALAU', 'nationality' => 'Palauane', 'iso_code_2' => 'PW', 'iso_code_3' => 'PLW', 'phone_code' => '680', 'continent' => 'OC', 'is_active' => true],
            ['id' => 586, 'name' => 'PAKISTAN', 'nationality' => 'Pakistanaise', 'iso_code_2' => 'PK', 'iso_code_3' => 'PAK', 'phone_code' => '92', 'continent' => 'AS', 'is_active' => true],
            ['id' => 591, 'name' => 'PANAMA', 'nationality' => 'Panaméenne', 'iso_code_2' => 'PA', 'iso_code_3' => 'PAN', 'phone_code' => '507', 'continent' => 'NA', 'is_active' => true],
            ['id' => 598, 'name' => 'PAPOUASIE-NOUVELLE-GUINÉE', 'nationality' => 'Papouane-Néo-Guinéenne', 'iso_code_2' => 'PG', 'iso_code_3' => 'PNG', 'phone_code' => '675', 'continent' => 'OC', 'is_active' => true],
            ['id' => 600, 'name' => 'PARAGUAY', 'nationality' => 'Paraguayenne', 'iso_code_2' => 'PY', 'iso_code_3' => 'PRY', 'phone_code' => '595', 'continent' => 'SA', 'is_active' => true],
            ['id' => 604, 'name' => 'PÉROU', 'nationality' => 'Péruvienne', 'iso_code_2' => 'PE', 'iso_code_3' => 'PER', 'phone_code' => '51', 'continent' => 'SA', 'is_active' => true],
            ['id' => 608, 'name' => 'PHILIPPINES', 'nationality' => 'Philippine', 'iso_code_2' => 'PH', 'iso_code_3' => 'PHL', 'phone_code' => '63', 'continent' => 'AS', 'is_active' => true],
            ['id' => 612, 'name' => 'ÎLES PITCAIRN', 'nationality' => 'Britannique', 'iso_code_2' => 'PN', 'iso_code_3' => 'PCN', 'phone_code' => '870', 'continent' => 'OC', 'is_active' => true],
            ['id' => 616, 'name' => 'POLOGNE', 'nationality' => 'Polonaise', 'iso_code_2' => 'PL', 'iso_code_3' => 'POL', 'phone_code' => '48', 'continent' => 'EU', 'is_active' => true],
            ['id' => 620, 'name' => 'PORTUGAL', 'nationality' => 'Portugaise', 'iso_code_2' => 'PT', 'iso_code_3' => 'PRT', 'phone_code' => '351', 'continent' => 'EU', 'is_active' => true],
            ['id' => 624, 'name' => 'GUINÉE-BISSAU', 'nationality' => 'Bissau-Guinéenne', 'iso_code_2' => 'GW', 'iso_code_3' => 'GNB', 'phone_code' => '245', 'continent' => 'AF', 'is_active' => true],
            ['id' => 626, 'name' => 'TIMOR-LESTE', 'nationality' => 'Est-Timoraise', 'iso_code_2' => 'TL', 'iso_code_3' => 'TLS', 'phone_code' => '670', 'continent' => 'AS', 'is_active' => true],
            ['id' => 630, 'name' => 'PORTO RICO', 'nationality' => 'Américaine', 'iso_code_2' => 'PR', 'iso_code_3' => 'PRI', 'phone_code' => '1787', 'continent' => 'NA', 'is_active' => true],
            ['id' => 634, 'name' => 'QATAR', 'nationality' => 'Qatarienne', 'iso_code_2' => 'QA', 'iso_code_3' => 'QAT', 'phone_code' => '974', 'continent' => 'AS', 'is_active' => true],
            ['id' => 638, 'name' => 'RÉUNION', 'nationality' => 'Française', 'iso_code_2' => 'RE', 'iso_code_3' => 'REU', 'phone_code' => '262', 'continent' => 'AF', 'is_active' => true],
            ['id' => 642, 'name' => 'ROUMANIE', 'nationality' => 'Roumaine', 'iso_code_2' => 'RO', 'iso_code_3' => 'ROU', 'phone_code' => '40', 'continent' => 'EU', 'is_active' => true],
            ['id' => 643, 'name' => 'RUSSIE', 'nationality' => 'Russe', 'iso_code_2' => 'RU', 'iso_code_3' => 'RUS', 'phone_code' => '7', 'continent' => 'EU', 'is_active' => true],
            ['id' => 646, 'name' => 'RWANDA', 'nationality' => 'Rwandaise', 'iso_code_2' => 'RW', 'iso_code_3' => 'RWA', 'phone_code' => '250', 'continent' => 'AF', 'is_active' => true],
            ['id' => 652, 'name' => 'SAINT BARTHÉLEMY', 'nationality' => 'Française', 'iso_code_2' => 'BL', 'iso_code_3' => 'BLM', 'phone_code' => '590', 'continent' => 'NA', 'is_active' => true],
            ['id' => 654, 'name' => 'SAINTE-HÉLÈNE', 'nationality' => 'Britannique', 'iso_code_2' => 'SH', 'iso_code_3' => 'SHN', 'phone_code' => '290', 'continent' => 'AF', 'is_active' => true],
            ['id' => 659, 'name' => 'SAINT-CHRISTOPHE-ET-NIÉVÈS', 'nationality' => 'Kittitienne et Névicienne', 'iso_code_2' => 'KN', 'iso_code_3' => 'KNA', 'phone_code' => '1869', 'continent' => 'NA', 'is_active' => true],
            ['id' => 660, 'name' => 'ANGUILLA', 'nationality' => 'Britannique', 'iso_code_2' => 'AI', 'iso_code_3' => 'AIA', 'phone_code' => '1264', 'continent' => 'NA', 'is_active' => true],
            ['id' => 662, 'name' => 'SAINTE-LUCIE', 'nationality' => 'Sainte-Lucienne', 'iso_code_2' => 'LC', 'iso_code_3' => 'LCA', 'phone_code' => '1758', 'continent' => 'NA', 'is_active' => true],
            ['id' => 663, 'name' => 'SAINT-MARTIN (PARTIE FRANÇAISE)', 'nationality' => 'Française', 'iso_code_2' => 'MF', 'iso_code_3' => 'MAF', 'phone_code' => '590', 'continent' => 'NA', 'is_active' => true],
            ['id' => 666, 'name' => 'SAINT-PIERRE-ET-MIQUELON', 'nationality' => 'Française', 'iso_code_2' => 'PM', 'iso_code_3' => 'SPM', 'phone_code' => '508', 'continent' => 'NA', 'is_active' => true],
            ['id' => 670, 'name' => 'SAINT-VINCENT-ET-LES GRENADINES', 'nationality' => 'Vincentienne', 'iso_code_2' => 'VC', 'iso_code_3' => 'VCT', 'phone_code' => '1784', 'continent' => 'NA', 'is_active' => true],
            ['id' => 674, 'name' => 'SAINT-MARIN', 'nationality' => 'Saint-Marinaise', 'iso_code_2' => 'SM', 'iso_code_3' => 'SMR', 'phone_code' => '378', 'continent' => 'EU', 'is_active' => true],
            ['id' => 678, 'name' => 'SÃO TOMÉ-ET-PRINCIPE', 'nationality' => 'Santoméenne', 'iso_code_2' => 'ST', 'iso_code_3' => 'STP', 'phone_code' => '239', 'continent' => 'AF', 'is_active' => true],
            ['id' => 682, 'name' => 'ARABIE SAOUDITE', 'nationality' => 'Saoudienne', 'iso_code_2' => 'SA', 'iso_code_3' => 'SAU', 'phone_code' => '966', 'continent' => 'AS', 'is_active' => true],
            ['id' => 686, 'name' => 'SÉNÉGAL', 'nationality' => 'Sénégalaise', 'iso_code_2' => 'SN', 'iso_code_3' => 'SEN', 'phone_code' => '221', 'continent' => 'AF', 'is_active' => true],
            ['id' => 688, 'name' => 'SERBIE', 'nationality' => 'Serbe', 'iso_code_2' => 'RS', 'iso_code_3' => 'SRB', 'phone_code' => '381', 'continent' => 'EU', 'is_active' => true],
            ['id' => 690, 'name' => 'SEYCHELLES', 'nationality' => 'Seychelloise', 'iso_code_2' => 'SC', 'iso_code_3' => 'SYC', 'phone_code' => '248', 'continent' => 'AF', 'is_active' => true],
            ['id' => 694, 'name' => 'SIERRA LEONE', 'nationality' => 'Sierra-Léonaise', 'iso_code_2' => 'SL', 'iso_code_3' => 'SLE', 'phone_code' => '232', 'continent' => 'AF', 'is_active' => true],
            ['id' => 702, 'name' => 'SINGAPOUR', 'nationality' => 'Singapourienne', 'iso_code_2' => 'SG', 'iso_code_3' => 'SGP', 'phone_code' => '65', 'continent' => 'AS', 'is_active' => true],
            ['id' => 703, 'name' => 'SLOVAQUIE', 'nationality' => 'Slovaque', 'iso_code_2' => 'SK', 'iso_code_3' => 'SVK', 'phone_code' => '421', 'continent' => 'EU', 'is_active' => true],
            ['id' => 704, 'name' => 'VIETNAM', 'nationality' => 'Vietnamienne', 'iso_code_2' => 'VN', 'iso_code_3' => 'VNM', 'phone_code' => '84', 'continent' => 'AS', 'is_active' => true],
            ['id' => 705, 'name' => 'SLOVÉNIE', 'nationality' => 'Slovène', 'iso_code_2' => 'SI', 'iso_code_3' => 'SVN', 'phone_code' => '386', 'continent' => 'EU', 'is_active' => true],
            ['id' => 706, 'name' => 'SOMALIE', 'nationality' => 'Somalienne', 'iso_code_2' => 'SO', 'iso_code_3' => 'SOM', 'phone_code' => '252', 'continent' => 'AF', 'is_active' => true],
            ['id' => 710, 'name' => 'AFRIQUE DU SUD', 'nationality' => 'Sud-Africaine', 'iso_code_2' => 'ZA', 'iso_code_3' => 'ZAF', 'phone_code' => '27', 'continent' => 'AF', 'is_active' => true],
            ['id' => 716, 'name' => 'ZIMBABWE', 'nationality' => 'Zimbabwéenne', 'iso_code_2' => 'ZW', 'iso_code_3' => 'ZWE', 'phone_code' => '263', 'continent' => 'AF', 'is_active' => true],
            ['id' => 724, 'name' => 'ESPAGNE', 'nationality' => 'Espagnole', 'iso_code_2' => 'ES', 'iso_code_3' => 'ESP', 'phone_code' => '34', 'continent' => 'EU', 'is_active' => true],
            ['id' => 728, 'name' => 'SOUDAN DU SUD', 'nationality' => 'Sud-Soudanaise', 'iso_code_2' => 'SS', 'iso_code_3' => 'SSD', 'phone_code' => '211', 'continent' => 'AF', 'is_active' => true],
            ['id' => 729, 'name' => 'SOUDAN', 'nationality' => 'Soudanaise', 'iso_code_2' => 'SD', 'iso_code_3' => 'SDN', 'phone_code' => '249', 'continent' => 'AF', 'is_active' => true],
            ['id' => 732, 'name' => 'SAHARA OCCIDENTAL', 'nationality' => 'Sahraouie', 'iso_code_2' => 'EH', 'iso_code_3' => 'ESH', 'phone_code' => null, 'continent' => 'AF', 'is_active' => true],
            ['id' => 740, 'name' => 'SURINAME', 'nationality' => 'Surinamaise', 'iso_code_2' => 'SR', 'iso_code_3' => 'SUR', 'phone_code' => '597', 'continent' => 'SA', 'is_active' => true],
            ['id' => 744, 'name' => 'SVALBARD ET ÎLE JAN MAYEN', 'nationality' => 'Norvégienne', 'iso_code_2' => 'SJ', 'iso_code_3' => 'SJM', 'phone_code' => '47', 'continent' => 'EU', 'is_active' => true],
            ['id' => 748, 'name' => 'ESWATINI', 'nationality' => 'Swazie', 'iso_code_2' => 'SZ', 'iso_code_3' => 'SWZ', 'phone_code' => '268', 'continent' => 'AF', 'is_active' => true],
            ['id' => 752, 'name' => 'SUÈDE', 'nationality' => 'Suédoise', 'iso_code_2' => 'SE', 'iso_code_3' => 'SWE', 'phone_code' => '46', 'continent' => 'EU', 'is_active' => true],
            ['id' => 756, 'name' => 'SUISSE', 'nationality' => 'Suisse', 'iso_code_2' => 'CH', 'iso_code_3' => 'CHE', 'phone_code' => '41', 'continent' => 'EU', 'is_active' => true],
            ['id' => 760, 'name' => 'SYRIE', 'nationality' => 'Syrienne', 'iso_code_2' => 'SY', 'iso_code_3' => 'SYR', 'phone_code' => '963', 'continent' => 'AS', 'is_active' => true],
            ['id' => 762, 'name' => 'TADJIKISTAN', 'nationality' => 'Tadjik', 'iso_code_2' => 'TJ', 'iso_code_3' => 'TJK', 'phone_code' => '992', 'continent' => 'AS', 'is_active' => true],
            ['id' => 764, 'name' => 'THAÏLANDE', 'nationality' => 'Thaïlandaise', 'iso_code_2' => 'TH', 'iso_code_3' => 'THA', 'phone_code' => '66', 'continent' => 'AS', 'is_active' => true],
            ['id' => 768, 'name' => 'TOGO', 'nationality' => 'Togolaise', 'iso_code_2' => 'TG', 'iso_code_3' => 'TGO', 'phone_code' => '228', 'continent' => 'AF', 'is_active' => true],
            ['id' => 772, 'name' => 'TOKELAU', 'nationality' => 'Néo-Zélandaise', 'iso_code_2' => 'TK', 'iso_code_3' => 'TKL', 'phone_code' => '690', 'continent' => 'OC', 'is_active' => true],
            ['id' => 776, 'name' => 'TONGA', 'nationality' => 'Tongienne', 'iso_code_2' => 'TO', 'iso_code_3' => 'TON', 'phone_code' => '676', 'continent' => 'OC', 'is_active' => true],
            ['id' => 780, 'name' => 'TRINITÉ-ET-TOBAGO', 'nationality' => 'Trinidadienne', 'iso_code_2' => 'TT', 'iso_code_3' => 'TTO', 'phone_code' => '1868', 'continent' => 'NA', 'is_active' => true],
            ['id' => 784, 'name' => 'ÉMIRATS ARABES UNIS', 'nationality' => 'Émirienne', 'iso_code_2' => 'AE', 'iso_code_3' => 'ARE', 'phone_code' => '971', 'continent' => 'AS', 'is_active' => true],
            ['id' => 788, 'name' => 'TUNISIE', 'nationality' => 'Tunisienne', 'iso_code_2' => 'TN', 'iso_code_3' => 'TUN', 'phone_code' => '216', 'continent' => 'AF', 'is_active' => true],
            ['id' => 792, 'name' => 'TURQUIE', 'nationality' => 'Turque', 'iso_code_2' => 'TR', 'iso_code_3' => 'TUR', 'phone_code' => '90', 'continent' => 'AS', 'is_active' => true],
            ['id' => 795, 'name' => 'TURKMÉNISTAN', 'nationality' => 'Turkmène', 'iso_code_2' => 'TM', 'iso_code_3' => 'TKM', 'phone_code' => '993', 'continent' => 'AS', 'is_active' => true],
            ['id' => 796, 'name' => 'ÎLES TURQUES ET CAÏQUES', 'nationality' => 'Britannique', 'iso_code_2' => 'TC', 'iso_code_3' => 'TCA', 'phone_code' => '1649', 'continent' => 'NA', 'is_active' => true],
            ['id' => 798, 'name' => 'TUVALU', 'nationality' => 'Tuvaluane', 'iso_code_2' => 'TV', 'iso_code_3' => 'TUV', 'phone_code' => '688', 'continent' => 'OC', 'is_active' => true],
            ['id' => 800, 'name' => 'OUGANDA', 'nationality' => 'Ougandaise', 'iso_code_2' => 'UG', 'iso_code_3' => 'UGA', 'phone_code' => '256', 'continent' => 'AF', 'is_active' => true],
            ['id' => 804, 'name' => 'UKRAINE', 'nationality' => 'Ukrainienne', 'iso_code_2' => 'UA', 'iso_code_3' => 'UKR', 'phone_code' => '380', 'continent' => 'EU', 'is_active' => true],
            ['id' => 807, 'name' => 'MACÉDOINE DU NORD', 'nationality' => 'Macédonienne', 'iso_code_2' => 'MK', 'iso_code_3' => 'MKD', 'phone_code' => '389', 'continent' => 'EU', 'is_active' => true],
            ['id' => 818, 'name' => 'ÉGYPTE', 'nationality' => 'Égyptienne', 'iso_code_2' => 'EG', 'iso_code_3' => 'EGY', 'phone_code' => '20', 'continent' => 'AF', 'is_active' => true],
            ['id' => 826, 'name' => 'ROYAUME-UNI', 'nationality' => 'Britannique', 'iso_code_2' => 'GB', 'iso_code_3' => 'GBR', 'phone_code' => '44', 'continent' => 'EU', 'is_active' => true],
            ['id' => 831, 'name' => 'GUERNESEY', 'nationality' => 'Britannique', 'iso_code_2' => 'GG', 'iso_code_3' => 'GGY', 'phone_code' => null, 'continent' => 'EU', 'is_active' => true],
            ['id' => 832, 'name' => 'JERSEY', 'nationality' => 'Britannique', 'iso_code_2' => 'JE', 'iso_code_3' => 'JEY', 'phone_code' => '44', 'continent' => 'EU', 'is_active' => true],
            ['id' => 833, 'name' => 'ÎLE DE MAN', 'nationality' => 'Britannique', 'iso_code_2' => 'IM', 'iso_code_3' => 'IMN', 'phone_code' => '44', 'continent' => 'EU', 'is_active' => true],
            ['id' => 834, 'name' => 'TANZANIE', 'nationality' => 'Tanzanienne', 'iso_code_2' => 'TZ', 'iso_code_3' => 'TZA', 'phone_code' => '255', 'continent' => 'AF', 'is_active' => true],
            ['id' => 840, 'name' => "ÉTATS-UNIS D'AMÉRIQUE", 'nationality' => 'Américaine', 'iso_code_2' => 'US', 'iso_code_3' => 'USA', 'phone_code' => '1', 'continent' => 'NA', 'is_active' => true],
            ['id' => 850, 'name' => 'ÎLES VIERGES DES ÉTATS-UNIS', 'nationality' => 'Américaine', 'iso_code_2' => 'VI', 'iso_code_3' => 'VIR', 'phone_code' => '1340', 'continent' => 'NA', 'is_active' => true],
            ['id' => 854, 'name' => 'BURKINA FASO', 'nationality' => 'Burkinabè', 'iso_code_2' => 'BF', 'iso_code_3' => 'BFA', 'phone_code' => '226', 'continent' => 'AF', 'is_active' => true],
            ['id' => 858, 'name' => 'URUGUAY', 'nationality' => 'Uruguayenne', 'iso_code_2' => 'UY', 'iso_code_3' => 'URY', 'phone_code' => '598', 'continent' => 'SA', 'is_active' => true],
            ['id' => 860, 'name' => 'OUZBÉKISTAN', 'nationality' => 'Ouzbek', 'iso_code_2' => 'UZ', 'iso_code_3' => 'UZB', 'phone_code' => '7', 'continent' => 'AS', 'is_active' => true],
            ['id' => 862, 'name' => 'VENEZUELA', 'nationality' => 'Vénézuélienne', 'iso_code_2' => 'VE', 'iso_code_3' => 'VEN', 'phone_code' => '58', 'continent' => 'SA', 'is_active' => true],
            ['id' => 876, 'name' => 'WALLIS-ET-FUTUNA', 'nationality' => 'Française', 'iso_code_2' => 'WF', 'iso_code_3' => 'WLF', 'phone_code' => '681', 'continent' => 'OC', 'is_active' => true],
            ['id' => 882, 'name' => 'SAMOA', 'nationality' => 'Samoane', 'iso_code_2' => 'WS', 'iso_code_3' => 'WSM', 'phone_code' => '685', 'continent' => 'OC', 'is_active' => true],
            ['id' => 887, 'name' => 'YÉMEN', 'nationality' => 'Yéménite', 'iso_code_2' => 'YE', 'iso_code_3' => 'YEM', 'phone_code' => '967', 'continent' => 'AS', 'is_active' => true],
            ['id' => 894, 'name' => 'ZAMBIE', 'nationality' => 'Zambienne', 'iso_code_2' => 'ZM', 'iso_code_3' => 'ZMB', 'phone_code' => '260', 'continent' => 'AF', 'is_active' => true],
        ];

        $now = now();
        foreach ($countries as &$country) {
            $country['created_at'] = $now;
            $country['updated_at'] = $now;
        }

        // Met à jour la table existante sur la base de la clé primaire (id)
        DB::table('countries')->upsert(
            $countries,
            ['id'], // Clé unique d'identification
            ['name', 'nationality', 'iso_code_2', 'iso_code_3', 'phone_code', 'continent', 'is_active', 'updated_at'] // Champs à mettre à jour
        );
    }
}